lesson_3
ekayumov/Java_script pull request #3
Opened 2022-07-20 02:44 UTC by ekayumov

2022-07-20 10:04 UTC, fanisco requested changes

2022-07-20 10:04 UTC, fanisco commented on lesson__3/lesson_3.js
> +        return historyArray
Поехала табуляция

2022-07-20 10:04 UTC, fanisco commented on lesson__3/lesson_3.js
> +        return "оператор '"+ key +"' cохранен"
Лучше возвращать просто булево

2022-07-20 10:04 UTC, fanisco commented on lesson__3/lesson_3.js
> +  let operationsArray = {}
Тип данных не обязательно отражать в названии

2022-07-20 10:04 UTC, fanisco commented on lesson__3/lesson_3.js
> +    else { return "оператор '" + operator + "' не найден"}
Обычно в таких случаях выбрасывают исключения

2022-07-20 10:04 UTC, fanisco commented on lesson__3/lesson_3.js
> +    const namberFirst = Number(arrayText[0])
number

2022-07-20 10:04 UTC, fanisco commented on lesson__3/lesson_3.js
> +cal.addOperation('+', (a, b) => a + b) // оператор '+' cохранен
Не хватает вычитания. К тому же, я бы внес сложение и вычитание во внутрь класса, чтобы не приходилось добавлять эти операции каждый раз, когда вызываешь калькулятор

2022-07-20 10:04 UTC, fanisco commented on lesson__3/lesson_3.js
> +const calculator = function () {
Классы принято именовать с большой буквы

2022-07-20 10:04 UTC, fanisco commented on lesson__3/lesson_3.js
> +}
Это не относится к решению? (=

2022-07-20 10:04 UTC, fanisco commented on lesson__3/lesson_4.js
> +const tiWi = function () {
Если это класс, то должен именоваться с большой буквы

2022-07-20 10:04 UTC, fanisco commented on lesson__3/lesson_4.js
> +    сoncertArray[сoncert] = {tickets_sold: [], price: price}
Использование `dashed_case`

2022-07-20 10:04 UTC, fanisco commented on lesson__3/lesson_4.js
> +  let сoncertArray = {}
Не обязательно в названии отражать тип данных. К тому же, в названии слово `Array`, а по факту создается объект. Помогает в наименовании объектов-коллекций и массивов plural-форма соответвующих английских слов:
concert - concerts
item - items
event - events
child - children
etc.

2022-07-20 10:04 UTC, fanisco commented on lesson__3/lesson_4.js
> +  let сoncertArray = {}
Вроде как переменная не меняет свое значение, можно использовать ключевое слово `const`

2022-07-20 10:04 UTC, fanisco commented on lesson__3/lesson_4.js
> +  }
Вроде этот метод не нужен по заданию?

2022-07-20 10:04 UTC, fanisco commented on lesson__3/lesson_4.js
> +    var max = Math.floor(999999);
Не стоит использовать ключевое слово var в том же документе (файле, модуле), где используется ES6 синтаксис

2022-07-20 10:04 UTC, fanisco commented on lesson__3/lesson_4.js
> +    var tiketIndex = myArray.indexOf(ticket);
Над этим участком кода стоит поработать - какие называния переменных и ключевые слова используются

2022-07-20 10:26 UTC, ekayumov commented on lesson__3/lesson_4.js
> +  }
Да знаю, просто сделал для удобства, так немного проще смотреть какие данные у нас сейчас есть

2022-07-20 20:31 UTC, fanisco commented on lesson__3/lesson_3.js
> +const calculator = function () {
Тут никаких изменений )=

2022-07-20 20:31 UTC, fanisco commented on lesson__3/lesson_3.js
> +}
И тут?

2022-07-20 20:33 UTC, fanisco requested changes

2022-07-20 20:33 UTC, fanisco commented on lesson__3/lesson_3.js
> +cal.addOperation('+', (a, b) => a + b) // false
По прежнему нет вычитания )=
И повторюсь по внесение базовых операций внутрь класса, чтобы не приходилось определять их самостоятельно

2022-07-20 20:33 UTC, fanisco commented on lesson__3/lesson_4.js
> +const tiWi = function () {
Напоминаю про это

2022-07-20 21:51 UTC, ekayumov commented on lesson__3/lesson_3.js
> +}
эту же часть кода я убрал

2022-07-21 07:53 UTC, fanisco commented on lesson__3/lesson_4.js
> +    var n = getRandomInt(сoncert)
Ключевое слово var

2022-07-27 06:57 UTC, merged