lesson 4
ekayumov/Java_script pull request #4
Opened 2022-07-27 11:27 UTC by ekayumov

2022-07-27 14:48 UTC, fanisco requested changes

2022-07-27 14:48 UTC, fanisco commented on lesson__4/lesson_4.js
> +  this.full = full // true / false
Этот флаг отвечает за целостность? Тогда должно быть что-то вроде `broken` или `unbroken`

2022-07-27 14:48 UTC, fanisco commented on lesson__4/lesson_4.js
> +  }
Комментарий верный. Типов кораблей/верфей может быть больше - а у них в конструкторах может быть разное количество аргументов.

2022-07-27 14:48 UTC, fanisco commented on lesson__4/lesson_4.js
> +// Реализовать 2 разных типа верфей, каждая из которых должна будет специализироваться на своем типе кораблей
Этот пункт не реализован. Должно получится 4 класса - 2 верфи и 2 корабля.

2022-07-27 14:48 UTC, fanisco commented on lesson__4/lesson_4.js
> +const Ship = function(full, collor) {
Корабль должен сразу создаваться целый без дополнительного уточнения.

2022-07-27 15:00 UTC, fanisco requested changes

2022-07-27 15:00 UTC, fanisco commented on lesson__4/lesson_3.js
> +const human_john = new Human("John", "Smith", "Russia", "+1234567890" )
Необходимо соблюдать единый стиль в называниях переменных/функций/классов, в данном случае - использование нижнего подчеркивания `_` лишнее

2022-07-27 15:00 UTC, fanisco commented on lesson__4/lesson_3.js
> +  this.startVacation: function () {}
Кажется тут поехало форматирование

2022-07-27 15:00 UTC, fanisco commented on lesson__4/lesson_3.js
> +EmployeeStatus.prototype = employer_john
Тут то же самое, что в предыдущих двух замечаниях

2022-07-27 15:00 UTC, fanisco commented on lesson__4/lesson_3.js
> +EmployeeStatus.prototype = employer_john
Тут должно было быть один или два (на выбор) класса - CurrentEmployee и FormerEmployee, реализация последнего необходима.
Нужно не забывать о цепочке наследования прототипов: FormerEmployee -> Employee -> Human. У каждого класса должна иметься возможность создать экземляр с полным набором данных, за исключением тех, что не представлены в классе. Например, создавая экземляр Employee, мы создаем сущность, которая является сотрудником, но и человеком. Это значит, мы должны иметь возможность передать не только должность, но и имя и т.п.

2022-07-27 18:48 UTC, ekayumov commented on lesson__4/lesson_4.js
> +// Реализовать 2 разных типа верфей, каждая из которых должна будет специализироваться на своем типе кораблей
ну фактически)))) это две разные ферфи, одна не может чинить корабли другого типа))))

2022-07-28 07:32 UTC, fanisco commented on lesson__4/lesson_4.js
> +  this.enginePower = params[:enginePower] // Мощность двигателя
`Uncaught SyntaxError: Unexpected token ':'`

2022-07-28 07:32 UTC, fanisco commented on lesson__4/lesson_4.js
> +SailShip.prototype = new Ship("синий")
Типы кораблей сразу с цветом?

2022-07-28 07:37 UTC, fanisco approved these changes

2022-08-02 15:23 UTC, merged